import { useState } from "react";
import { DetailDrawer } from "../components/DetailDrawer";
import { SectionCard } from "../components/SectionCard";
import { StatusBadge } from "../components/StatusBadge";
import { formatTimestamp } from "../lib/utils";

const statusOptions = ["New", "Triage", "Investigating", "Contained", "Resolved", "Closed"];
const dispositionOptions = [
  { label: "True Positive", value: "True Positive" },
  { label: "False Positive", value: "False Positive" },
  { label: "Benign Positive", value: "Benign" },
];

export function CasesPage({ cases, loadCaseDetail, runResponseAction, runCaseWorkflow }) {
  const [selectedCase, setSelectedCase] = useState(null);
  const [loadingDetail, setLoadingDetail] = useState(false);
  const [runningAction, setRunningAction] = useState("");
  const [ownerInput, setOwnerInput] = useState("");
  const [noteInput, setNoteInput] = useState("");
  const [statusInput, setStatusInput] = useState("Investigating");
  const [dispositionInput, setDispositionInput] = useState("True Positive");
  const [workflowMessage, setWorkflowMessage] = useState("");

  async function openCaseDetail(rowid) {
    setLoadingDetail(true);
    setWorkflowMessage("");
    try {
      const detail = await loadCaseDetail(rowid);
      setSelectedCase(detail);
      setOwnerInput(detail?.owner && detail.owner !== "Local SOC Pipeline" ? detail.owner : "");
      setStatusInput(detail?.status || "Investigating");
      setDispositionInput(detail?.disposition || "True Positive");
      setNoteInput("");
    } finally {
      setLoadingDetail(false);
    }
  }

  async function handleResponseAction(action) {
    if (!selectedCase) {
      return;
    }
    setRunningAction(action);
    setWorkflowMessage("");
    try {
      const result = await runResponseAction({
        action,
        target_type: "case",
        target_rowid: selectedCase.rowid,
      });
      const nextDetail = await loadCaseDetail(selectedCase.rowid);
      setSelectedCase(nextDetail);
      setWorkflowMessage(result?.audit_entry?.content || "Response action completed.");
    } finally {
      setRunningAction("");
    }
  }

  async function handleWorkflowUpdate(payload, message) {
    if (!selectedCase) {
      return;
    }
    setRunningAction("workflow");
    setWorkflowMessage("");
    try {
      const result = await runCaseWorkflow({
        case_rowid: selectedCase.rowid,
        ...payload,
      });
      setSelectedCase(result?.case || await loadCaseDetail(selectedCase.rowid));
      setWorkflowMessage(result?.audit_entry?.content || message);
      setNoteInput("");
    } finally {
      setRunningAction("");
    }
  }

  return (
    <>
      <SectionCard
        title="Cases"
        subtitle="Correlated case records generated by the local-dev SOC pipeline."
      >
        <div className="grid gap-4 xl:grid-cols-2">
          {cases.map((item) => (
            <button
              key={item.rowid}
              type="button"
              onClick={() => openCaseDetail(item.rowid)}
              className="rounded-2xl border border-white/10 bg-black/20 p-5 text-left transition hover:border-cyan-400/20 hover:bg-white/[0.03]"
            >
              <div className="flex items-start justify-between gap-3">
                <div>
                  <h3 className="text-lg font-medium text-white">{item.title}</h3>
                  <p className="mt-2 text-sm text-slate-400">Case ID: {item.rowid}</p>
                </div>
                <StatusBadge value={item.status} />
              </div>

              <div className="mt-4 grid gap-3 md:grid-cols-2">
                <div className="rounded-2xl border border-white/10 bg-white/[0.03] p-3">
                  <div className="text-xs uppercase tracking-[0.18em] text-slate-500">Priority</div>
                  <div className="mt-2 text-sm text-white">{item.priority || "Unset"}</div>
                </div>
                <div className="rounded-2xl border border-white/10 bg-white/[0.03] p-3">
                  <div className="text-xs uppercase tracking-[0.18em] text-slate-500">Linked Alerts</div>
                  <div className="mt-2 text-sm text-white">{item.linked_alerts}</div>
                </div>
                <div className="rounded-2xl border border-white/10 bg-white/[0.03] p-3">
                  <div className="text-xs uppercase tracking-[0.18em] text-slate-500">Owner</div>
                  <div className="mt-2 text-sm text-white">{item.owner || "Local SOC Pipeline"}</div>
                </div>
                <div className="rounded-2xl border border-white/10 bg-white/[0.03] p-3">
                  <div className="text-xs uppercase tracking-[0.18em] text-slate-500">Playbook</div>
                  <div className="mt-2 text-sm text-white">{item.playbook || "Not queued"}</div>
                </div>
              </div>

              <p className="mt-4 text-sm leading-6 text-slate-400">{item.summary || "No summary available."}</p>
              <div className="mt-4 text-xs text-slate-500">Updated {formatTimestamp(item.last_updated)}</div>
            </button>
          ))}
        </div>
      </SectionCard>

      <DetailDrawer
        open={Boolean(selectedCase)}
        title={selectedCase?.title || "Case detail"}
        subtitle={selectedCase?.rowid}
        onClose={() => setSelectedCase(null)}
      >
        {loadingDetail && !selectedCase ? <div className="text-sm text-slate-400">Loading case detail...</div> : null}
        {selectedCase ? (
          <div className="space-y-6">
            <div className="flex flex-wrap gap-2">
              <StatusBadge value={selectedCase.status} />
              {selectedCase.priority ? <StatusBadge value={selectedCase.priority} /> : null}
              {selectedCase.disposition ? <StatusBadge value={selectedCase.disposition} /> : null}
            </div>

            <div className="rounded-2xl border border-white/10 bg-black/20 p-4">
              <div className="text-xs uppercase tracking-[0.18em] text-slate-500">Case Summary</div>
              <p className="mt-3 text-sm leading-6 text-slate-200">{selectedCase.summary || "No summary available."}</p>
            </div>

            <div className="grid gap-4 md:grid-cols-2">
              <div className="rounded-2xl border border-white/10 bg-black/20 p-4">
                <div className="text-xs uppercase tracking-[0.18em] text-slate-500">Assignment</div>
                <div className="mt-2 text-sm text-white">{selectedCase.assignment?.owner || selectedCase.owner || "Local SOC Pipeline"}</div>
                <div className="mt-1 text-xs text-slate-500">{selectedCase.assignment?.assigned ? "Assigned" : "Unassigned queue"}</div>
              </div>
              <div className="rounded-2xl border border-white/10 bg-black/20 p-4">
                <div className="text-xs uppercase tracking-[0.18em] text-slate-500">SLA Timer</div>
                <div className="mt-2 text-sm text-white">
                  {selectedCase.sla?.remaining_minutes ?? "--"} min remaining / {selectedCase.sla?.target_minutes ?? "--"} min target
                </div>
                <div className="mt-1 text-xs text-slate-500">
                  {selectedCase.sla?.breached ? "SLA breached" : `${selectedCase.sla?.elapsed_minutes ?? 0} min elapsed`}
                </div>
              </div>
            </div>

            <div className="grid gap-4 md:grid-cols-2">
              <div className="rounded-2xl border border-white/10 bg-black/20 p-4">
                <div className="text-xs uppercase tracking-[0.18em] text-slate-500">Owner</div>
                <div className="mt-2 text-sm text-white">{selectedCase.owner || "Local SOC Pipeline"}</div>
              </div>
              <div className="rounded-2xl border border-white/10 bg-black/20 p-4">
                <div className="text-xs uppercase tracking-[0.18em] text-slate-500">Disposition</div>
                <div className="mt-2 text-sm text-white">{selectedCase.disposition || "Undispositioned"}</div>
              </div>
            </div>

            <div className="rounded-2xl border border-white/10 bg-black/20 p-4">
              <div className="text-xs uppercase tracking-[0.18em] text-slate-500">Case Workflow</div>
              <div className="mt-4 grid gap-4 md:grid-cols-2">
                <div>
                  <label className="block text-xs uppercase tracking-[0.18em] text-slate-500">Assign owner</label>
                  <div className="mt-2 flex gap-2">
                    <input
                      value={ownerInput}
                      onChange={(event) => setOwnerInput(event.target.value)}
                      placeholder="analyst@company.local"
                      className="h-11 flex-1 rounded-2xl border border-white/10 bg-ink-900/80 px-4 text-sm text-white outline-none focus:border-cyan-400/40"
                    />
                    <button
                      type="button"
                      onClick={() => handleWorkflowUpdate({ owner: ownerInput }, "Owner updated.")}
                      className="rounded-2xl border border-cyan-400/20 bg-cyan-400/10 px-4 text-sm text-cyan-100 transition hover:bg-cyan-400/20"
                    >
                      Save
                    </button>
                  </div>
                </div>

                <div>
                  <label className="block text-xs uppercase tracking-[0.18em] text-slate-500">Change status</label>
                  <div className="mt-2 flex gap-2">
                    <select
                      value={statusInput}
                      onChange={(event) => setStatusInput(event.target.value)}
                      className="h-11 flex-1 rounded-2xl border border-white/10 bg-ink-900/80 px-4 text-sm text-white outline-none focus:border-cyan-400/40"
                    >
                      {statusOptions.map((option) => <option key={option} value={option}>{option}</option>)}
                    </select>
                    <button
                      type="button"
                      onClick={() => handleWorkflowUpdate({ status: statusInput }, "Status updated.")}
                      className="rounded-2xl border border-cyan-400/20 bg-cyan-400/10 px-4 text-sm text-cyan-100 transition hover:bg-cyan-400/20"
                    >
                      Apply
                    </button>
                  </div>
                </div>
              </div>

              <div className="mt-4 grid gap-4 md:grid-cols-[1fr_auto]">
                <div>
                  <label className="block text-xs uppercase tracking-[0.18em] text-slate-500">Add analyst note</label>
                  <textarea
                    value={noteInput}
                    onChange={(event) => setNoteInput(event.target.value)}
                    rows={4}
                    placeholder="Add a note about investigation progress, evidence, or next steps."
                    className="mt-2 w-full rounded-2xl border border-white/10 bg-ink-900/80 px-4 py-3 text-sm text-white outline-none focus:border-cyan-400/40"
                  />
                </div>
                <button
                  type="button"
                  onClick={() => handleWorkflowUpdate({ note: noteInput }, "Note added.")}
                  className="h-11 self-end rounded-2xl border border-cyan-400/20 bg-cyan-400/10 px-4 text-sm text-cyan-100 transition hover:bg-cyan-400/20"
                >
                  Add Note
                </button>
              </div>

              <div className="mt-4">
                <label className="block text-xs uppercase tracking-[0.18em] text-slate-500">Close case with disposition</label>
                <div className="mt-2 flex gap-2">
                  <select
                    value={dispositionInput}
                    onChange={(event) => setDispositionInput(event.target.value)}
                    className="h-11 flex-1 rounded-2xl border border-white/10 bg-ink-900/80 px-4 text-sm text-white outline-none focus:border-cyan-400/40"
                  >
                    {dispositionOptions.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}
                  </select>
                  <button
                    type="button"
                    onClick={() => handleWorkflowUpdate({ disposition: dispositionInput }, "Disposition updated.")}
                    className="rounded-2xl border border-emerald-400/20 bg-emerald-400/10 px-4 text-sm text-emerald-100 transition hover:bg-emerald-400/20"
                  >
                    Close Case
                  </button>
                </div>
              </div>

              {workflowMessage ? (
                <div className="mt-4 rounded-2xl border border-emerald-400/20 bg-emerald-400/10 px-3 py-2 text-xs text-emerald-100">
                  {workflowMessage}
                </div>
              ) : null}
            </div>

            <div className="rounded-2xl border border-white/10 bg-black/20 p-4">
              <div className="text-xs uppercase tracking-[0.18em] text-slate-500">Playbook Runs</div>
              <div className="mt-3 space-y-3">
                {(selectedCase.linked_playbooks || []).map((item) => (
                  <div key={item.rowid} className="rounded-2xl border border-white/10 bg-white/[0.03] p-3">
                    <div className="flex items-center justify-between gap-3">
                      <div className="text-sm text-white">{item.name}</div>
                      <StatusBadge value={item.status} />
                    </div>
                    <div className="mt-2 text-xs text-slate-500">Started {formatTimestamp(item.started_at)}</div>
                  </div>
                ))}
              </div>
            </div>

            <div className="rounded-2xl border border-white/10 bg-black/20 p-4">
              <div className="text-xs uppercase tracking-[0.18em] text-slate-500">Linked Alerts</div>
              <div className="mt-3 space-y-3">
                {(selectedCase.related_alerts || selectedCase.alerts || []).map((alert) => (
                  <div key={alert.rowid} className="rounded-2xl border border-white/10 bg-white/[0.03] p-3">
                    <div className="flex items-center justify-between gap-3">
                      <div className="text-sm text-white">{alert.title}</div>
                      <StatusBadge value={alert.severity} />
                    </div>
                    <div className="mt-2 text-xs text-slate-500">{alert.rule_id}</div>
                  </div>
                ))}
              </div>
            </div>

            <div className="rounded-2xl border border-white/10 bg-black/20 p-4">
              <div className="text-xs uppercase tracking-[0.18em] text-slate-500">Linked Assets</div>
              <div className="mt-3 grid gap-3 md:grid-cols-2">
                {(selectedCase.linked_assets || []).length ? (selectedCase.linked_assets || []).map((asset) => (
                  <div key={asset.rowid} className="rounded-2xl border border-white/10 bg-white/[0.03] p-3">
                    <div className="flex items-center justify-between gap-3">
                      <div className="text-sm text-white">{asset.hostname}</div>
                      <StatusBadge value={asset.status} />
                    </div>
                    <div className="mt-2 text-xs text-slate-500">{asset.owner} | {asset.criticality}</div>
                  </div>
                )) : <div className="text-sm text-slate-400">No linked assets derived from related alerts.</div>}
              </div>
            </div>

            <div className="rounded-2xl border border-white/10 bg-black/20 p-4">
              <div className="text-xs uppercase tracking-[0.18em] text-slate-500">Artifacts</div>
              <div className="mt-3 grid gap-3 md:grid-cols-3 text-sm">
                <div>
                  <div className="text-slate-500">Actors</div>
                  <div className="mt-2 space-y-1 text-white">
                    {(selectedCase.artifact_summary?.actors || []).slice(0, 6).map((item) => (
                      <div key={item.rowid}>{item.value}</div>
                    ))}
                  </div>
                </div>
                <div>
                  <div className="text-slate-500">Targets</div>
                  <div className="mt-2 space-y-1 text-white">
                    {(selectedCase.artifact_summary?.targets || []).slice(0, 6).map((item) => (
                      <div key={item.rowid}>{item.value}</div>
                    ))}
                  </div>
                </div>
                <div>
                  <div className="text-slate-500">Related</div>
                  <div className="mt-2 space-y-1 text-white">
                    {(selectedCase.artifact_summary?.related || []).slice(0, 6).map((item) => (
                      <div key={item.rowid}>{item.value}</div>
                    ))}
                  </div>
                </div>
              </div>
            </div>

            <div className="rounded-2xl border border-white/10 bg-black/20 p-4">
              <div className="text-xs uppercase tracking-[0.18em] text-slate-500">Attack Timeline</div>
              <div className="mt-3 space-y-3">
                {(selectedCase.attack_timeline || []).length ? (selectedCase.attack_timeline || []).map((item) => (
                  <div key={item.rowid} className="rounded-2xl border border-white/10 bg-white/[0.03] p-3">
                    <div className="flex items-center justify-between gap-3">
                      <div className="flex items-center gap-2">
                        <StatusBadge value={item.type || "event"} />
                        {item.severity ? <StatusBadge value={item.severity} /> : null}
                      </div>
                      <div className="text-xs text-slate-500">{formatTimestamp(item.ts)}</div>
                    </div>
                    <div className="mt-2 text-sm text-white">{item.title || "Case event"}</div>
                    <div className="mt-1 text-sm leading-6 text-slate-300">{item.summary || "No summary available."}</div>
                  </div>
                )) : <div className="text-sm text-slate-400">No attack timeline available yet.</div>}
              </div>
            </div>

            <div className="rounded-2xl border border-white/10 bg-black/20 p-4">
              <div className="text-xs uppercase tracking-[0.18em] text-slate-500">Activity Timeline</div>
              <div className="mt-3 space-y-3">
                {(selectedCase.activity_timeline || selectedCase.recent_messages || []).map((item) => (
                  <div key={item.rowid} className="rounded-2xl border border-white/10 bg-white/[0.03] p-3">
                    <div className="flex items-center justify-between gap-3">
                      <StatusBadge value={item.role || item.action} />
                      <div className="text-xs text-slate-500">{formatTimestamp(item.ts)}</div>
                    </div>
                    <div className="mt-2 text-sm leading-6 text-slate-200">{item.content || item.data || item.details?.summary}</div>
                  </div>
                ))}
              </div>
            </div>

            <div className="rounded-2xl border border-white/10 bg-black/20 p-4">
              <div className="text-xs uppercase tracking-[0.18em] text-slate-500">Analyst Notes</div>
              <div className="mt-3 space-y-2 text-sm text-slate-200">
                {(selectedCase.notes || []).length ? (selectedCase.notes || []).map((note, index) => (
                  <div key={`${note.ts}-${index}`} className="rounded-xl border border-white/10 bg-white/[0.03] px-3 py-2">
                    <div className="text-xs text-slate-500">{note.author}</div>
                    <div className="mt-1">{note.content}</div>
                  </div>
                )) : <div className="text-slate-400">No notes yet.</div>}
              </div>
            </div>

            <div className="rounded-2xl border border-white/10 bg-black/20 p-4">
              <div className="text-xs uppercase tracking-[0.18em] text-slate-500">Response History</div>
              <div className="mt-3 space-y-3">
                {(selectedCase.response_history || []).length ? (selectedCase.response_history || []).map((item) => (
                  <div key={item.rowid} className="rounded-2xl border border-white/10 bg-white/[0.03] p-3">
                    <div className="flex items-center justify-between gap-3">
                      <StatusBadge value={item.action || item.role} />
                      <div className="text-xs text-slate-500">{formatTimestamp(item.ts)}</div>
                    </div>
                    <div className="mt-2 text-sm leading-6 text-slate-200">{item.content || item.details?.summary}</div>
                  </div>
                )) : <div className="text-sm text-slate-400">No response history yet.</div>}
              </div>
            </div>

            <div className="rounded-2xl border border-white/10 bg-black/20 p-4">
              <div className="text-xs uppercase tracking-[0.18em] text-slate-500">Response Jobs</div>
              <div className="mt-3 space-y-3">
                {(selectedCase.response_jobs || []).length ? (selectedCase.response_jobs || []).map((item) => (
                  <div key={item.rowid} className="rounded-2xl border border-white/10 bg-white/[0.03] p-3">
                    <div className="flex items-center justify-between gap-3">
                      <StatusBadge value={item.action} />
                      <StatusBadge value={item.status} />
                    </div>
                    <div className="mt-2 text-sm leading-6 text-slate-200">{item.summary}</div>
                    <div className="mt-2 text-xs text-slate-500">
                      Started {formatTimestamp(item.started_at)} | Finished {formatTimestamp(item.finished_at)}
                    </div>
                  </div>
                )) : <div className="text-sm text-slate-400">No response jobs recorded for this case yet.</div>}
              </div>
            </div>

            <div className="rounded-2xl border border-white/10 bg-black/20 p-4">
              <div className="text-xs uppercase tracking-[0.18em] text-slate-500">Response Actions</div>
              <div className="mt-3 grid gap-3 md:grid-cols-2">
                {(selectedCase.recommended_actions || []).map((item) => (
                  <button
                    key={item.id}
                    type="button"
                    onClick={() => handleResponseAction(item.id)}
                    className="rounded-2xl border border-cyan-400/20 bg-cyan-400/10 p-3 text-left transition hover:bg-cyan-400/20"
                  >
                    <div className="text-sm font-medium text-cyan-100">
                      {runningAction === item.id ? "Running..." : item.label}
                    </div>
                    <div className="mt-2 text-xs leading-5 text-cyan-50/80">{item.description}</div>
                  </button>
                ))}
              </div>
            </div>
          </div>
        ) : null}
      </DetailDrawer>
    </>
  );
}
